### ISSUE TITLE
qrcode.getDecodeReadyStatus() never equal to 1

### ISSUE THREAD

**Issue by physio** [m5stack/M5Unit-QRCode#1]
### Describe the bug

I'm using a M5Stack Core S3 with QR-Code unit in I2C. I set the comunication with: qrcode.begin(&Wire, UNIT_QRCODE_ADDR, 12, 11, 100000U):

```c
    while (!qrcode.begin(&Wire, UNIT_QRCODE_ADDR, 12, 11, 100000U)) {
        canvas.println("Unit QRCode I2C Init Fail");
        Serial.println("Unit QRCode I2C Init Fail");
        canvas.pushSprite(0, 0);
        delay(1000);
    }
```

The program go in "Auto Scan Mode" but when with the unit I read a barcode the qrcode.getDecodeReadyStatus() not go to 1. The device read the code because it's beep.

### To reproduce

1. In arduino IDE 2.2.1, with M5CoreS3 board

### Expected behavior

I expect  that qrcode.getDecodeReadyStatus() go to 1

### Environment

- OS: windows 11
- IDE &IDE Version: Arduino 2.2.1
- Repository Version: master

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by TinyuZhao** [comment]
The internal I2C address of CoreS3 is 11,12
The unit you are using should use the external I2C interface, which should be 2,1
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/2a392f2c-b336-48ad-9993-cf4f6cc1a00b">

**Comment by physio** [comment]
Is it possible to reset the communication if the `getDecodeReadyStatus()` response method is equal to 2 (so I can retry to begin communication)?

**Comment by TinyuZhao** [comment]
> Is it possible to reset the communication if the `getDecodeReadyStatus()` response method is equal to 2 (so I can retry to begin communication)?

It might be better to reread.
<img width="282" alt="image" src="https://github.com/user-attachments/assets/434493ab-07a8-4503-83a2-c97df3ca500d">
